package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "APPLICANT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPLICANT_ID_GENERATOR", sequenceName = "APPLICANT_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "Personal Info")
	private demo.client.shared.Base base;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "Address")
	private demo.client.shared.Address address;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "Technologies")
	private demo.client.shared.Technologies technologies;

	@org.kie.api.definition.type.Label(value = "HR Notes")
	private java.lang.String notes;

	public Applicant() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public demo.client.shared.Base getBase() {
		return this.base;
	}

	public void setBase(demo.client.shared.Base base) {
		this.base = base;
	}

	public demo.client.shared.Address getAddress() {
		return this.address;
	}

	public void setAddress(demo.client.shared.Address address) {
		this.address = address;
	}

	public demo.client.shared.Technologies getTechnologies() {
		return this.technologies;
	}

	public void setTechnologies(demo.client.shared.Technologies technologies) {
		this.technologies = technologies;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public Applicant(java.lang.Long id, demo.client.shared.Base base,
			demo.client.shared.Address address,
			demo.client.shared.Technologies technologies, java.lang.String notes) {
		this.id = id;
		this.base = base;
		this.address = address;
		this.technologies = technologies;
		this.notes = notes;
	}

}