package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Technologies implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "TECHNOLOGIES_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "TECHNOLOGIES_ID_GENERATOR", sequenceName = "TECHNOLOGIES_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Java?")
	private java.lang.Boolean hasJavaSkill;

	@org.kie.api.definition.type.Label("Drools?")
	private java.lang.Boolean hasDroolsSkill;

	@org.kie.api.definition.type.Label("jBPM?")
	private java.lang.Boolean hasJBPMSkill;

	@org.kie.api.definition.type.Label("JavaScript?")
	private java.lang.Boolean hasJavaScriptSkill;

	@org.kie.api.definition.type.Label("AngularJS?")
	private java.lang.Boolean hasAngularSkill;

	@org.kie.api.definition.type.Label("HTML/CSS?")
	private java.lang.Boolean hasHTMLCSSSkill;

	public Technologies() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean isHasJavaSkill() {
		return this.hasJavaSkill;
	}

	public void setHasJavaSkill(java.lang.Boolean hasJavaSkill) {
		this.hasJavaSkill = hasJavaSkill;
	}

	public java.lang.Boolean isHasDroolsSkill() {
		return this.hasDroolsSkill;
	}

	public void setHasDroolsSkill(java.lang.Boolean hasDroolsSkill) {
		this.hasDroolsSkill = hasDroolsSkill;
	}

	public java.lang.Boolean isHasJBPMSkill() {
		return this.hasJBPMSkill;
	}

	public void setHasJBPMSkill(java.lang.Boolean hasJBPMSkill) {
		this.hasJBPMSkill = hasJBPMSkill;
	}

	public java.lang.Boolean isHasJavaScriptSkill() {
		return this.hasJavaScriptSkill;
	}

	public void setHasJavaScriptSkill(java.lang.Boolean hasJavaScriptSkill) {
		this.hasJavaScriptSkill = hasJavaScriptSkill;
	}

	public java.lang.Boolean isHasAngularSkill() {
		return this.hasAngularSkill;
	}

	public void setHasAngularSkill(java.lang.Boolean hasAngularSkill) {
		this.hasAngularSkill = hasAngularSkill;
	}

	public java.lang.Boolean isHasHTMLCSSSkill() {
		return this.hasHTMLCSSSkill;
	}

	public void setHasHTMLCSSSkill(java.lang.Boolean hasHTMLCSSSkill) {
		this.hasHTMLCSSSkill = hasHTMLCSSSkill;
	}

	public Technologies(java.lang.Long id, java.lang.Boolean hasJavaSkill,
			java.lang.Boolean hasDroolsSkill, java.lang.Boolean hasJBPMSkill,
			java.lang.Boolean hasJavaScriptSkill, java.lang.Boolean hasAngularSkill,
			java.lang.Boolean hasHTMLCSSSkill) {
		this.id = id;
		this.hasJavaSkill = hasJavaSkill;
		this.hasDroolsSkill = hasDroolsSkill;
		this.hasJBPMSkill = hasJBPMSkill;
		this.hasJavaScriptSkill = hasJavaScriptSkill;
		this.hasAngularSkill = hasAngularSkill;
		this.hasHTMLCSSSkill = hasHTMLCSSSkill;
	}

}